name: XAI-2D3D-RegQuality_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - opencv-python
      - pandas
      - pyyaml
      - matplotlib
      - optuna
      - numpy
      - tqdm
